### ISSUE TITLE
Hide DocumentUNID based on configuration coming from server

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Portal#1]
We would like to hide DocumentUNID column in DataGrid based on configuration provided from server side.

**Comment by piotrzarzycki21** [comment]
@JoelProminic first part of this issue is for you I believe.

**Comment by JoelProminic** [comment]
We should also hide DocumentationUNID in the form, using the same field.

**Comment by JoelProminic** [comment]
Proposed properties for the configuration agent:

Property | Default | Description 
-- | -- | --
ui_documentation_editable | false | `true` if the Getting Started UI should be editable, `false` otherwise
ui_documentation_show_unid | false | `true` if the DocumentationUNID column should be displayed, false otherwise.
ui_title | "Super.Human.Portal" | The title for the application.  This may be customized with the server name or the organizational certifier.

**Comment by JoelProminic** [comment]
The DocumentUNID column and field should be displayed if `ui_documentation_show_unid` is `true`, and hidden otherwise.

**Comment by piotrzarzycki21** [comment]
I have started working on this. I was able load your config, but I need to do quite a bit changes in UI to get it work properly. It should be ready for tomorrow rather today.

**Comment by piotrzarzycki21** [comment]
Hiding/showing based on configuration from server sight has been applied. It's merged to main.

**Comment by JoelProminic** [comment]
I confirmed that the column was hidden, but the field was not hidden in the form.  This is an addition we requested last week:
![image](https://user-images.githubusercontent.com/24532731/217319356-293fb635-ebbf-4b1e-8ef9-27ed0c9278a6.png)

On a side note, the header and page title were updated based on ui_documentation_editable, as expected.

**Comment by piotrzarzycki21** [comment]
> I confirmed that the column was hidden, but the field was not hidden in the form. This is an addition we requested last week:

@JoelProminic This has been fixed.

**Comment by piotrzarzycki21** [comment]
I don't think there is anything more to do in this issue. I'm closing it.
